# Generated by Django 4.0.8 on 2024-04-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
