# Generated by Django 3.2.4 on 2024-05-22 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_remove_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='posts/'),
            preserve_default=False,
        ),
    ]
